image: maven:3-eclipse-temurin-21-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn install -B

test:
  stage: test
  script:
    - mvn test

production:
  stage: production
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week