image: maven:3-eclipse-temurin-21-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn build
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test:
  stage: testgti
  script:
    - mvn test