name: WorldSystem
version: 2.0.3
author: Butzlabben
main: de.butzlabben.world.WorldSystem

commands:
  ws:
    description: Commands for WorldSystem
    usage: /ws
  ws get:
    usage: /ws get
  ws help:
    usage: /ws help
  ws home:
    usage: /ws home
  ws addmember:
    usage: /ws addmember <player>
  ws delmember:
    usage: /ws delmember <player>
  ws leave:
    usage: /ws leave
  ws tp:
    usage: /ws tp <target>
  ws tnt:
    usage: /ws tnt
  ws fire:
    usage: /ws fire
  ws info:
    usage: /ws info
  ws togglebuild:
    usage: /ws togglebuild <player>
  ws togglegm:
    usage: /ws togglegm <player>
  ws toggletp:
    usage: /ws toggletp <player>
  ws reset:
    usage: /ws reset
  ws gui:
    usage: /ws gui
  ws delete:
    usage: /ws delete <player>
    permission: ws.delete
  ws confirm:
    usage: /ws confirm
    permission: ws.confirm

permissions:
  ws.*:
    default: op
    description: Gives '*'-Perms to all Commands
    children:
      ws.tp.*: true
      ws.tp.world: true
      ws.tp.toother: true
      ws.tp.other: true
      ws.build: true
      ws.gamemode: true
      ws.delete: true
      ws.lag: true
      ws.big: true
      ws.large: true
      ws.confirm: true
  ws.tp.*:
    default: op
    description: You can teleport everything
    children:
      ws.tp.toother: true
      ws.tp.other: true
      ws.tp.world: true
  ws.build:
    default: op
    description: You can build on other Worlds without WorldPermissions
  ws.delete:
    default: op
    description: You can delete a world
  ws.gamemode:
    default: op
    description: You can change GameMode on other worlds
  ws.tp.other:
    default: op
    description: You can teleport other persons
  ws.tp.toother:
    default: op
    description: You can teleport across worlds
  ws.tp.world:
    default: op
    description: You can teleport to without rights World
  ws.lag:
    default: op
    description: You can see lag messages
  ws.big:
    default: op      
    description: Gives you a bigger world (if set)
  ws.large:
    default: op
    children:
      ws.big: true
    description: Gives you a even bigger world (if set)
  ws.confirm:
    default: op
    description: You can confirm (if needed) an auto-update
    
default-permission: admin